version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: asiayo
    container_name: asiayo
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
      - ./node_modules:/var/www/node_modules
    ports:
      - "8080:8080"